clc; clear; close all;

params = config.getHyperparams();
fprintf('Target device: %s\n', params.ExecutionEnvironment);

utils.downloadMNIST(params.DataDir);
[imdsTrain, imdsVal] = data.getDatastores(params.DataDir);

net = models.createCNN([28 28 1], 10);

options = trainingOptions('adam', ...
    'InitialLearnRate', params.InitialLearnRate, ...
    'MaxEpochs', params.MaxEpochs, ...
    'MiniBatchSize', params.MiniBatchSize, ...
    'ValidationData', imdsVal, ...
    'ValidationFrequency', 30, ...
    'ExecutionEnvironment', params.ExecutionEnvironment, ...
    'Shuffle', 'every-epoch', ...
    'Verbose', true, ...
    'Plots', 'training-progress');

[net, info] = trainnet(imdsTrain, net, 'crossentropy', options);

outputPath = fullfile(pwd, 'trained_mnist_model.mat');
save(outputPath, 'net', 'info');
fprintf('\nModel saved to: %s\n', outputPath);